version: "3"

services:
  caltrops:
    container_name: caltrops
    privileged: true
    image: jas0ndiamond/caltrops:latest
    ports:
      - "13128-13148:13128-13148"
      - "15000:15000"
    restart: "no"
